[build]
  # Directorio donde se encuentra el código fuente
  base = "/"
  
  # Comando para construir el sitio
  command = "npm run build"
  
  # Directorio que se desplegará (debe coincidir con outDir en vite.config.js)
  publish = "dist"

# Configuración para SPA - redirige todas las rutas no encontradas a index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de encabezados para mejorar la seguridad y el rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Cache-Control = "public, max-age=3600"

# Configuración específica para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"